In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel(r'C:\Users\Danish\Desktop\Data_sets\Day - 30 - All Practice files\Day - 30 - Mobile Sales Data.xlsx')

In [4]:
df.head()

,Transaction ID,Day,Month,Year,Day Name,Brand,Units Sold,Price Per Unit,Customer Name,Customer Age,City,Payment Method,Customer Ratings,Mobile Model
0,1,9,10,2021,Sat,Xiaomi,6,10174.70,Lalita Ahuja,38,Ludhiana,UPI,5,Redmi Note 10
1,2,9,10,2021,Saturday,Vivo,6,10565.19,Sneha Sharma,37,Delhi,Credit Card,3,Vivo Y51
2,3,9,10,2021,Saturday,Vivo,8,58527.58,Radha Srivastava,40,Mumbai,UPI,5,Vivo S1
3,4,10,10,2021,Sunday,Xiaomi,5,25563.98,Bhavana Arora,21,Mumbai,Credit Card,4,Mi 11
4,5,10,10,2021,Sunday,OnePlus,3,48168.02,Sneha Mehta,38,Gorakhpur,Cash,5,OnePlus 9

In [5]:
# Combine Day, Month, and Year columns into a single Date column
df['Date'] = pd.to_datetime(df[['Year', 'Month', 'Day']])

# Display the first few rows to verify the new column
df.head()

,Transaction ID,Day,Month,Year,Day Name,Brand,Units Sold,Price Per Unit,Customer Name,Customer Age,City,Payment Method,Customer Ratings,Mobile Model,Date
0,1,9,10,2021,Sat,Xiaomi,6,10174.70,Lalita Ahuja,38,Ludhiana,UPI,5,Redmi Note 10,2021-10-09
1,2,9,10,2021,Saturday,Vivo,6,10565.19,Sneha Sharma,37,Delhi,Credit Card,3,Vivo Y51,2021-10-09
2,3,9,10,2021,Saturday,Vivo,8,58527.58,Radha Srivastava,40,Mumbai,UPI,5,Vivo S1,2021-10-09
3,4,10,10,2021,Sunday,Xiaomi,5,25563.98,Bhavana Arora,21,Mumbai,Credit Card,4,Mi 11,2021-10-10
4,5,10,10,2021,Sunday,OnePlus,3,48168.02,Sneha Mehta,38,Gorakhpur,Cash,5,OnePlus 9,2021-10-10

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3835 entries, 0 to 3834
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3835 non-null   int64
 1   Day               3835 non-null   int64
 2   Month             3835 non-null   int64
 3   Year              3835 non-null   int64
 4   Day Name          3835 non-null   object
 5   Brand             3835 non-null   object
 6   Units Sold        3835 non-null   int64
 7   Price Per Unit    3835 non-null   float64
 8   Customer Name     3835 non-null   object
 9   Customer Age      3835 non-null   int64
 10  City              3835 non-null   object
 11  Payment Method    3835 non-null   object
 12  Customer Ratings  3835 non-null   int64
 13  Mobile Model      3835 non-null   object
 14  Date              3835 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(7), object(6)
memory usage: 449.5+ KB

In [7]:
df.to_excel('output_file.xlsx', index=False)