# Inverse encodin/ Inverse transform /Decoding categorical variables

Inverse encoding is the process of converting the encoded data back to its original form. This is done by using the `inverse_transform()` method. This method is available for the following encoders:

- `LabelEncoder`
- `OrdinalEncoder`
- `OneHotEncoder`

In [42]:
# import libraries
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [43]:
# load the data
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [44]:
# impute missing values for age, embarked, embark_town and deck
df['age'].fillna(df['age'].median(), inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0], inplace=True)
# drop deck column
df.drop('deck', axis=1, inplace=True)

In [45]:
# encode all categorical variables and object variables

le_sex = LabelEncoder()
le_embarked = LabelEncoder()
le_class = LabelEncoder()
le_who = LabelEncoder()
le_embark_town = LabelEncoder()
le_alive = LabelEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])
df['class'] = le_class.fit_transform(df['class'])
df['who'] = le_who.fit_transform(df['who'])
df['embark_town'] = le_embark_town.fit_transform(df['embark_town'])
df['alive'] = le_alive.fit_transform(df['alive'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [46]:
# inverse transform the data

df['sex'] = le_sex.inverse_transform(df['sex'])
df['embarked'] = le_embarked.inverse_transform(df['embarked'])
df['class'] = le_class.inverse_transform(df['class'])
df['who'] = le_who.inverse_transform(df['who'])
df['embark_town'] = le_embark_town.inverse_transform(df['embark_town'])
df['alive'] = le_alive.inverse_transform(df['alive'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

# one hot encoding

In [50]:
from sklearn.preprocessing import OneHotEncoder

df = sns.load_dataset('titanic')

cat_columns = ['sex', 'embarked']

encoder = OneHotEncoder(sparse=False)
encoded_df = pd.DataFrame(encoder.fit_transform(df[cat_columns]))

# concatenate the dataframes 
df = pd.concat([df, encoded_df], axis=1)
# df.drop(cat_columns, axis=1, inplace=True)
df.head()

/Users/babaaammar/mambaforge/envs/python_ml/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,...,deck,embark_town,alive,alone,0,1,2,3,4,5
0,0,3,male,22.0,1,0,7.2500,S,Third,man,...,NaN,Southampton,no,False,0.0,1.0,0.0,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,...,C,Cherbourg,yes,False,1.0,0.0,1.0,0.0,0.0,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,...,NaN,Southampton,yes,True,1.0,0.0,0.0,0.0,1.0,0.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,...,C,Southampton,yes,False,1.0,0.0,0.0,0.0,1.0,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,...,NaN,Southampton,no,True,0.0,1.0,0.0,0.0,1.0,0.0

In [56]:
# We need to extract the original categories for each encoded column
original_categories = {col: encoder.categories_[i] for i, col in enumerate(cat_columns)}
# Manual creation of feature names
feature_names = []
for i, col in enumerate(cat_columns):
    for category in encoder.categories_[i]:
        feature_names.append(f"{col}_{category}")

encoded_df = pd.DataFrame(encoded_df, columns=feature_names)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,...,deck,embark_town,alive,alone,0,1,2,3,4,5
0,0,3,male,22.0,1,0,7.2500,S,Third,man,...,NaN,Southampton,no,False,0.0,1.0,0.0,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,...,C,Cherbourg,yes,False,1.0,0.0,1.0,0.0,0.0,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,...,NaN,Southampton,yes,True,1.0,0.0,0.0,0.0,1.0,0.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,...,C,Southampton,yes,False,1.0,0.0,0.0,0.0,1.0,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,...,NaN,Southampton,no,True,0.0,1.0,0.0,0.0,1.0,0.0

# Assignment: Use Ordinal Encoder with Inverse Transform Method.

In [ ]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder
import numpy as np # Needed for NaN handling

# Load the dataset
df = sns.load_dataset('titanic')

# Define the categorical columns
cat_columns = ['sex', 'embarked']

# Handle NaN values in 'embarked' before encoding
# OrdinalEncoder by default propagates NaNs, but for inverse_transform to work cleanly
# on a subset of columns, it's often best to impute/fill them first.
# For simplicity, we'll fill with a placeholder for now, as was potentially done in the OHE example.
# Let's fill NaNs in 'embarked' with the most frequent value (S)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
# The 'sex' column has no NaNs, so no filling is needed for it.

# 1. Initialize the OrdinalEncoder
# We don't specify categories, so it will determine them automatically and encode them alphabetically.
# To handle NaN values in inverse_transform, we explicitly set handle_unknown='use_encoded_value'
# and unknown_value=np.nan, but since we filled NaNs, we can just use default 'error'.
ordinal_encoder = OrdinalEncoder()

# 2. Fit and Transform the categorical columns
encoded_data_array = ordinal_encoder.fit_transform(df[cat_columns])

# 3. Create a DataFrame for the encoded data
# The columns are now numerical codes (e.g., 0, 1, 2, ...)
encoded_df_oe = pd.DataFrame(encoded_data_array, columns=[f'{col}_encoded_oe' for col in cat_columns])

# Display the first few rows of the encoded data
print("Encoded Data (First 5 Rows):")
print(encoded_df_oe.head())

print("\n---")

# **4. Use inverse_transform to convert the encoded data back to the original categories**
decoded_data_array = ordinal_encoder.inverse_transform(encoded_data_array)

# 5. Create a DataFrame for the decoded data
decoded_df = pd.DataFrame(decoded_data_array, columns=[f'{col}_decoded_oe' for col in cat_columns])

# Display the first few rows of the decoded data
print("Decoded Data (First 5 Rows):")
print(decoded_df.head())

print("\n---")

# Display the categories learned by the encoder
print("Categories learned by the OrdinalEncoder:")
for i, col in enumerate(cat_columns):
    print(f"Feature '{col}': {ordinal_encoder.categories_[i]}")

# You can also concatenate the encoded/decoded data with the original DataFrame if needed
df_with_oe = pd.concat([df.reset_index(drop=True), encoded_df_oe, decoded_df], axis=1)
print("\nOriginal, Encoded, and Decoded Data (First 5 Rows):")
print(df_with_oe[['sex', 'sex_encoded_oe', 'sex_decoded_oe', 'embarked', 'embarked_encoded_oe', 'embarked_decoded_oe']].head())

In Machine Learning, **Inverse Transform** is the process of converting scaled or encoded data back into its original, human-readable format.

As a Data Scientist, this is a critical step because while your model needs numbers like `0.231` or `1`, your business stakeholders (or your COVID-19 dashboard users) need to see `"High Risk"` or `"Islamabad"`.

---

## 1. Which Encoders are Reversible?

Most standard encoders in `scikit-learn` are designed to be reversible because they store a **Mapping Dictionary** or **Internal Statistics** during the `.fit()` process.

### ✅ Fully Reversible (Built-in `inverse_transform`)

These encoders keep a memory of what they did.

| Encoder | What it does | How it Reverses |
| --- | --- | --- |
| **LabelEncoder** | Maps categories to $0, 1, 2...$ | It looks up the integer in its `classes_` attribute. |
| **OneHotEncoder** | Creates binary columns ($0$ or $1$). | It finds which column has the $1$ and maps it back to the category. |
| **OrdinalEncoder** | Maps categories to an ordered scale. | Similar to LabelEncoder, it uses the category list. |
| **StandardScaler** | $(x - \mu) / \sigma$ | Multiplies by $\sigma$ and adds $\mu$ back. |
| **MinMaxScaler** | Scales to $0-1$ range. | Uses the stored `min` and `max` to stretch it back. |

### ❌ Non-Reversible (Lossy)

These encoders destroy information during the transformation, making a perfect reverse impossible.

* **Hash Encoder:** Uses a mathematical hash function (like MD5) to map strings to numbers. Since multiple strings can result in the same hash ("collision"), you cannot go backward.
* **Target Encoder (usually):** It replaces a category with the average value of the target variable. Since many categories could have the same average, the original labels are lost.
* **Discretizer (KBinsDiscretizer):** It turns a continuous number (like Age: 25) into a bin (like "20-30"). You can't know if the original age was 21, 25, or 29.

---

## 2. The Logic of `inverse_transform`

To reverse a transformation, the encoder must be **fitted** first. The `.fit()` step is where the encoder "learns" the map.

**Example in Python:**

```python
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
original = ['Lodhran', 'Islamabad', 'Lodhran']

# 1. Transform
encoded = le.fit_transform(original) 
# Result: [1, 0, 1]

# 2. Reverse Transform
decoded = le.inverse_transform([1, 0, 1])
# Result: ['Lodhran', 'Islamabad', 'Lodhran']

```

---

## 3. Critical Warning: The "Pipeline" Trap

If you use a **Pipeline**, you cannot simply call `pipeline.inverse_transform(y_pred)`.

The pipeline often expects the input to have the same number of columns as the original training data. If you scaled 10 features, you must provide 10 columns to the `inverse_transform` method of the scaler.

**The Pro Solution:** Access the specific step of the pipeline:

```python
# Reverting only the target variable if it was scaled
y_original = pipeline.named_steps['scaler'].inverse_transform(y_pred.reshape(-1, 1))

```

---

## 4. Best Practices for your Portfolio

1. **Save your Encoders:** When you move your model from a Notebook to a real app, you **must** save the fitted encoder as a `.pkl` (pickle) file. If you create a new encoder in the app, it won't have the same mapping, and your predictions will be wrong.
2. **Avoid LabelEncoding for Features:** For your Bank Churn features, use `OneHotEncoder`. `LabelEncoder` should strictly be used for the **Target** ($y$) only.
3. **Check for "Unknowns":** When reversing `OneHotEncoder`, ensure you handled `handle_unknown='ignore'`. If the model sees a category it never saw in training, the inverse transform might throw an error or return `None`.

---

## Summary Table

| Goal | Method | Tool |
| --- | --- | --- |
| **Numeric -> Original Scale** | `scaler.inverse_transform()` | StandardScaler / MinMaxScaler |
| **Integer -> Category Name** | `le.inverse_transform()` | LabelEncoder / OrdinalEncoder |
| **Binary Matrix -> Category Name** | `ohe.inverse_transform()` | OneHotEncoder |

**Since you're working with the IMDb Global Film dataset, would you like to see how to reverse-transform "Genre" predictions so they show up as text in a final table?**