# Inverse encodin/ Inverse transform /Decoding categorical variables

Inverse encoding is the process of converting the encoded data back to its original form. This is done by using the `inverse_transform()` method. This method is available for the following encoders:

- `LabelEncoder`
- `OrdinalEncoder`
- `OneHotEncoder`

In [13]:
# import libraries
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [14]:
# load the data
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:
# impute missing values for age, embarked, embark_town and deck
df['age'].fillna(df['age'].median(), inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0], inplace=True)
# drop deck column
df.drop('deck', axis=1, inplace=True)

/tmp/ipython-input-741017295.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
/tmp/ipython-input-741017295.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
/tmp/ipython-input-741017295.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embark_town'].fillna(df['embark_town'].mode()[0], inplace=True)

In [16]:
# encode all categorical variables and object variables

le_sex = LabelEncoder()
le_embarked = LabelEncoder()
le_class = LabelEncoder()
le_who = LabelEncoder()
le_embark_town = LabelEncoder()
le_alive = LabelEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])
df['class'] = le_class.fit_transform(df['class'])
df['who'] = le_who.fit_transform(df['who'])
df['embark_town'] = le_embark_town.fit_transform(df['embark_town'])
df['alive'] = le_alive.fit_transform(df['alive'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [17]:
# inverse transform the data

df['sex'] = le_sex.inverse_transform(df['sex'])
df['embarked'] = le_embarked.inverse_transform(df['embarked'])
df['class'] = le_class.inverse_transform(df['class'])
df['who'] = le_who.inverse_transform(df['who'])
df['embark_town'] = le_embark_town.inverse_transform(df['embark_town'])
df['alive'] = le_alive.inverse_transform(df['alive'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

# one hot encoding

In [18]:
df = sns.load_dataset('titanic')

cat_columns = ['sex', 'embarked']

encoder = OneHotEncoder() # Removed sparse=False
encoded_data_array = encoder.fit_transform(df[cat_columns])

# concatenate the dataframes
encoded_df = pd.DataFrame(encoded_data_array.toarray(), columns=encoder.get_feature_names_out(cat_columns)) # Convert sparse matrix to dense array and get feature names
df = pd.concat([df, encoded_df], axis=1)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,...,deck,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0,3,male,22.0,1,0,7.2500,S,Third,man,...,NaN,Southampton,no,False,0.0,1.0,0.0,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,...,C,Cherbourg,yes,False,1.0,0.0,1.0,0.0,0.0,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,...,NaN,Southampton,yes,True,1.0,0.0,0.0,0.0,1.0,0.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,...,C,Southampton,yes,False,1.0,0.0,0.0,0.0,1.0,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,...,NaN,Southampton,no,True,0.0,1.0,0.0,0.0,1.0,0.0

In [19]:
# We need to extract the original categories for each encoded column
# original_categories = {col: encoder.categories_[i] for i, col in enumerate(cat_columns)} # This is not needed for inverse transform with OHE
# Manual creation of feature names
# feature_names = []
# for i, col in enumerate(cat_columns):
#     for category in encoder.categories_[i]:
#         feature_names.append(f"{col}_{category}")

# encoded_df = pd.DataFrame(encoded_data_array, columns=feature_names) # This is done in the previous cell

# To inverse transform OneHotEncoded data, you need the original encoder object and the encoded data (usually as a NumPy array or sparse matrix)
# Let's assume 'encoded_data_array' from the previous cell is available (it is a sparse matrix)

# 1. If you need to get the original dataframe back from the encoded data, you would typically do it column by column or merge.
# The inverse_transform method of OneHotEncoder is designed to work on the *encoded* columns only, not the entire dataframe.

# Example of inverse transforming a subset of the encoded columns back to original:
# Select the encoded columns from the concatenated dataframe
encoded_cols_in_df = [col for col in df.columns if col.startswith(('sex_', 'embarked_'))]
encoded_data_subset = df[encoded_cols_in_df]

# Inverse transform the selected columns
# Note: inverse_transform expects the data in the same order and format as fit_transform output
# It might be easier to inverse transform the original 'encoded_data_array' from the previous step.
decoded_data_array = encoder.inverse_transform(encoded_data_array)

# Convert the decoded array back to a DataFrame for better readability
decoded_df_ohe = pd.DataFrame(decoded_data_array, columns=cat_columns)

print("Original Data (First 5 Rows of relevant columns):")
print(df[cat_columns].head())

print("\n---")

print("Encoded Data (First 5 Rows of relevant columns):")
print(df[encoded_cols_in_df].head())

print("\n---")

print("Decoded Data (First 5 Rows):")
print(decoded_df_ohe.head())


# You can also concatenate the decoded data back if needed
# df_with_decoded_ohe = pd.concat([df.drop(columns=encoded_cols_in_df), decoded_df_ohe], axis=1)
# print("\nDataFrame with Decoded OHE Columns (First 5 Rows):")
# print(df_with_decoded_ohe.head())

Original Data (First 5 Rows of relevant columns):
      sex embarked
0    male        S
1  female        C
2  female        S
3  female        S
4    male        S

---
Encoded Data (First 5 Rows of relevant columns):
   sex_female  sex_male  embarked_C  embarked_Q  embarked_S  embarked_nan
0         0.0       1.0         0.0         0.0         1.0           0.0
1         1.0       0.0         1.0         0.0         0.0           0.0
2         1.0       0.0         0.0         0.0         1.0           0.0
3         1.0       0.0         0.0         0.0         1.0           0.0
4         0.0       1.0         0.0         0.0         1.0           0.0

---
Decoded Data (First 5 Rows):
      sex embarked
0    male        S
1  female        C
2  female        S
3  female        S
4    male        S

# Assignment: Use Ordinal Encoder with Inverse Transform Method.

In [20]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder
import numpy as np # Needed for NaN handling

# Load the dataset
df = sns.load_dataset('titanic')

# Define the categorical columns
cat_columns = ['sex', 'embarked']

# Handle NaN values in 'embarked' before encoding
# OrdinalEncoder by default propagates NaNs, but for inverse_transform to work cleanly
# on a subset of columns, it's often best to impute/fill them first.
# For simplicity, we'll fill with a placeholder for now, as was potentially done in the OHE example.
# Let's fill NaNs in 'embarked' with the most frequent value (S)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
# The 'sex' column has no NaNs, so no filling is needed for it.

# 1. Initialize the OrdinalEncoder
# We don't specify categories, so it will determine them automatically and encode them alphabetically.
# To handle NaN values in inverse_transform, we explicitly set handle_unknown='use_encoded_value'
# and unknown_value=np.nan, but since we filled NaNs, we can just use default 'error'.
ordinal_encoder = OrdinalEncoder()

# 2. Fit and Transform the categorical columns
encoded_data_array = ordinal_encoder.fit_transform(df[cat_columns])

# 3. Create a DataFrame for the encoded data
# The columns are now numerical codes (e.g., 0, 1, 2, ...)
encoded_df_oe = pd.DataFrame(encoded_data_array, columns=[f'{col}_encoded_oe' for col in cat_columns])

# Display the first few rows of the encoded data
print("Encoded Data (First 5 Rows):")
print(encoded_df_oe.head())

print("\n---")

# **4. Use inverse_transform to convert the encoded data back to the original categories**
decoded_data_array = ordinal_encoder.inverse_transform(encoded_data_array)

# 5. Create a DataFrame for the decoded data
decoded_df = pd.DataFrame(decoded_data_array, columns=[f'{col}_decoded_oe' for col in cat_columns])

# Display the first few rows of the decoded data
print("Decoded Data (First 5 Rows):")
print(decoded_df.head())

print("\n---")

# Display the categories learned by the encoder
print("Categories learned by the OrdinalEncoder:")
for i, col in enumerate(cat_columns):
    print(f"Feature '{col}': {ordinal_encoder.categories_[i]}")

# You can also concatenate the encoded/decoded data with the original DataFrame if needed
df_with_oe = pd.concat([df.reset_index(drop=True), encoded_df_oe, decoded_df], axis=1)
print("\nOriginal, Encoded, and Decoded Data (First 5 Rows):")
print(df_with_oe[['sex', 'sex_encoded_oe', 'sex_decoded_oe', 'embarked', 'embarked_encoded_oe', 'embarked_decoded_oe']].head())

/tmp/ipython-input-4055667383.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)

Encoded Data (First 5 Rows):
   sex_encoded_oe  embarked_encoded_oe
0             1.0                  2.0
1             0.0                  0.0
2             0.0                  2.0
3             0.0                  2.0
4             1.0                  2.0

---
Decoded Data (First 5 Rows):
  sex_decoded_oe embarked_decoded_oe
0           male                   S
1         female                   C
2         female                   S
3         female                   S
4           male                   S

---
Categories learned by the OrdinalEncoder:
Feature 'sex': ['female' 'male']
Feature 'embarked': ['C' 'Q' 'S']

Original, Encoded, and Decoded Data (First 5 Rows):
      sex  sex_encoded_oe sex_decoded_oe embarked  embarked_encoded_oe  \
0    male             1.0           male        S                  2.0
1  female             0.0         female        C                  0.0
2  female             0.0         female        S                  2.0
3  female             0.0         female        S                  2.0
4    male             1.0           male        S                  2.0

  embarked_decoded_oe
0                   S
1                   C
2                   S
3                   S
4                   S